---
- hosts: prod_switches
  connection: local
  gather_facts: false
  tasks:
    - name: Gather facts with SNMP version 2
      snmp_facts:
        host: "{{ inventory_hostname }}"
        version: v2c
        community: rocom

    - name: Display Uptime
      debug:
        msg: "The uptime of {{ inventory_hostname }} is {{ ansible_sysuptime }}"